default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e4
    memory_size: 64
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

BasicLearning:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 20
    beta: 5.0e-3
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 3
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9

DummyBrain: 
    trainer: ppo
    batch_size: 256
    beta: 1.5e-4
    buffer_size: 10240
    epsilon: 0.25
    gamma: 0.8
    hidden_units: 512
    lambd: 0.95
    learning_rate: 1.5e-5
    max_steps: 5000000000
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: true  
    use_curiosity: True
    curiosity_strength: 0.01
    curiosity_enc_size: 128

PPORBC: 
    trainer: ppo
    lambd: 0.92
    buffer_size: 204288
    batch_size: 512
    num_epoch: 3
    learning_rate: 1.5e-5
    time_horizon: 256
    max_steps: 1000000
    beta: 1.0e-3
    epsilon: 0.2
    normalize: false
    num_layers: 2
    hidden_units: 512
    summary_freq: 1000
    use_recurrent: true  
    sequence_Length: 4
    memory_size: 64
    pretraining:
        demo_path: C:/REPOS/master_deegree/Master-Degree/Assets/Demonstrations/5.demo
        strength: 0.5
        steps: 10000

PPOR: 
    trainer: ppo
    lambd: 0.92
    buffer_size: 204288
    batch_size: 512
    num_epoch: 3
    learning_rate: 1.5e-5
    time_horizon: 256
    max_steps: 1000000
    beta: 1.0e-3
    epsilon: 0.2
    normalize: false
    num_layers: 2
    hidden_units: 512
    summary_freq: 1000
    use_recurrent: true  
    sequence_Length: 4
    memory_size: 64

PPOBC: 
    trainer: ppo
    lambd: 0.92
    buffer_size: 204288
    batch_size: 512
    num_epoch: 3
    learning_rate: 1.5e-5
    time_horizon: 256
    max_steps: 1000000
    beta: 1.0e-3
    epsilon: 0.2
    normalize: false
    num_layers: 2
    hidden_units: 512
    summary_freq: 1000
    use_recurrent: false 
    pretraining:
        demo_path: C:/REPOS/master_deegree/Master-Degree/Assets/Demonstrations/5.demo
        strength: 0.5
        steps: 10000

PPO: 
    trainer: ppo
    lambd: 0.92
    buffer_size: 204288
    batch_size: 512
    num_epoch: 3
    learning_rate: 1.5e-5
    time_horizon: 256
    max_steps: 1000000
    beta: 1.0e-3
    epsilon: 0.2
    normalize: false
    num_layers: 2
    hidden_units: 512
    summary_freq: 1000
    use_recurrent: false 
